name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: download GoogleTest and build test
      run: |
            cd src
            git clone https://github.com/google/googletest.git -b release-1.11.0
            cd googletest
            mkdir build
            cd build
            cmake ..
            make
            sudo make install
    - name: run test
      run: |
        cd src
        make test_graph
