name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ os }}-latest
    strategy:
      os: [ubuntu, macos]

    steps:
    - uses: actions/checkout@v2
    - name: run test
      run: |
        bazel test --test_output=all //:all_tests
