name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: download GoogleTest and build test
      run: |
            cd src
            cmake -S . -B build
            cmake --build build
    - name: run test
      run: |
        cd src/build
        ctest
